### ISSUE TITLE
engraver didn't report the corresponding error information when ansible is missing

### ISSUE THREAD

**Issue by ghost** [onyx-platform/engraver#5]
i already attach the related log and code[init_command.py].

``` log
[root@namenode ~]# engraver init hello-world --example-app beginner
> Cloning beginner playbook via Git. Streaming Git output ...
Initialized empty Git repository in /root/hello-world/.git/
remote: Counting objects: 127, done.
remote: Total 127 (delta 0), reused 0 (delta 0), pack-reused 127
Receiving objects: 100% (127/127), 20.12 KiB, done.
Resolving deltas: 100% (61/61), done.
> Finished cloning example.

> Initializing .engraver folders ...
> Finished .engraver folder initialization.

> Creating new Ansible playbook. Streaming Ansible output ...
Traceback (most recent call last):
  File "/usr/bin/engraver", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/src/engraver.py", line 101, in main
    apply(fns.get(tuple(command_seq)), [arg_vars, project_root])
  File "/usr/local/lib/python2.7/site-packages/src/init_command.py", line 35, in init
    call(["ansible-galaxy", "init", ansible_dir])
  File "/usr/local/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

``` python
  print_ok_pending("Creating new Ansible playbook. Streaming Ansible output")
**  call(["ansible-galaxy", "init", ansible_dir])
  call(["cp", resource_filename(__name__, "ansible_template/ansible.cfg"), ansible_dir])
  call(["cp", resource_filename(__name__, "ansible_template/refresh_cache.yml"), ansible_dir])
  print_done("Finished executing Ansible.")
  print("")
```

**Comment by MichaelDrogalis** [comment]
Thanks! Looking like we never ended up wrapping those calls with error checks. I'll try to get to it this week.
